version: '3'
services:
  db:
    mysql:
      image: mysql:8.0
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      environnement:
        - MYSQL_DATABASE=
        - MYSQL_ROOT_PASSWORD= 

  maven:
    image: maven

  spring:
    image: spring

  application:
    image: dockerfacile/app
    ports:
      - 8080:8080